name: Deploy SheFi New

on:
  push:
    branches: [master]

jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup node and npm
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.CONTAINER_REGISTRY_NAME}}
          username: ${{secrets.CONTAINER_REGISTRY_KEY}}
          password: ${{secrets.CONTAINER_REGISTRY_KEY}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{secrets.CONTAINER_REGISTRY_NAME}}/shefi-new:latest
